# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\RAZNOE\prgrming\horsy\Source\client\uis\horsy_package.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.packagename_box = QtWidgets.QLineEdit(self.centralwidget)
        self.packagename_box.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.packagename_box.setStyleSheet("background-color: rgb(74, 76, 83);\n"
"border-radius: 5px;    \n"
"color: rgb(242, 242, 242);")
        self.packagename_box.setText("")
        self.packagename_box.setReadOnly(True)
        self.packagename_box.setObjectName("packagename_box")
        self.main_exe_box = QtWidgets.QLineEdit(self.centralwidget)
        self.main_exe_box.setGeometry(QtCore.QRect(20, 305, 291, 31))
        self.main_exe_box.setStyleSheet("background-color: rgb(74, 76, 83);\n"
"border-radius: 5px;    \n"
"color: rgb(242, 242, 242);")
        self.main_exe_box.setObjectName("main_exe_box")
        self.source_url_box = QtWidgets.QLineEdit(self.centralwidget)
        self.source_url_box.setGeometry(QtCore.QRect(20, 200, 291, 31))
        self.source_url_box.setStyleSheet("background-color: rgb(74, 76, 83);\n"
"border-radius: 5px;    \n"
"color: rgb(242, 242, 242);")
        self.source_url_box.setObjectName("source_url_box")
        self.url_of_exe_box = QtWidgets.QLineEdit(self.centralwidget)
        self.url_of_exe_box.setGeometry(QtCore.QRect(20, 165, 291, 31))
        self.url_of_exe_box.setStyleSheet("background-color: rgb(74, 76, 83);\n"
"border-radius: 5px;    \n"
"color: rgb(242, 242, 242);")
        self.url_of_exe_box.setObjectName("url_of_exe_box")
        self.dependency_url_box = QtWidgets.QLineEdit(self.centralwidget)
        self.dependency_url_box.setGeometry(QtCore.QRect(20, 235, 291, 31))
        self.dependency_url_box.setStyleSheet("background-color: rgb(74, 76, 83);\n"
"border-radius: 5px;    \n"
"color: rgb(242, 242, 242);")
        self.dependency_url_box.setObjectName("dependency_url_box")
        self.dependency_run_box = QtWidgets.QLineEdit(self.centralwidget)
        self.dependency_run_box.setGeometry(QtCore.QRect(20, 270, 291, 31))
        self.dependency_run_box.setStyleSheet("background-color: rgb(74, 76, 83);\n"
"border-radius: 5px;    \n"
"color: rgb(242, 242, 242);")
        self.dependency_run_box.setObjectName("dependency_run_box")
        self.package_desc_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.package_desc_box.setGeometry(QtCore.QRect(20, 60, 256, 101))
        self.package_desc_box.setStyleSheet("background-color: rgb(74, 76, 83);\n"
"border-radius: 5px;    \n"
"color: rgb(242, 242, 242);")
        self.package_desc_box.setAcceptRichText(False)
        self.package_desc_box.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.package_desc_box.setObjectName("package_desc_box")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setEnabled(True)
        self.update_button.setGeometry(QtCore.QRect(20, 360, 291, 50))
        self.update_button.setMinimumSize(QtCore.QSize(0, 50))
        self.update_button.setStyleSheet("QPushButton {\n"
"    color: rgb(204, 204, 204);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"    background-color: rgb(28, 30, 33);\n"
"    border-color: rgb(66, 143, 225);\n"
"}\n"
"QPushButton:hover{\n"
"    border-width: 2px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(50, 60, 63);\n"
"}\n"
"QPushButton:disabled{\n"
"    border-width: 0px;\n"
"    background-color: rgb(92, 99, 109);\n"
"}")
        self.update_button.setObjectName("update_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "horsy - editing package"))
        self.packagename_box.setPlaceholderText(_translate("MainWindow", "Editing package"))
        self.main_exe_box.setPlaceholderText(_translate("MainWindow", "Main executable command (file.exe, python main.py, etc)"))
        self.source_url_box.setPlaceholderText(_translate("MainWindow", "Url of source (project on GitHub, source archive)"))
        self.url_of_exe_box.setPlaceholderText(_translate("MainWindow", "Url of executable (ends on .exe or .zip)"))
        self.dependency_url_box.setPlaceholderText(_translate("MainWindow", "Dependency URL (installer in .exe)"))
        self.dependency_run_box.setPlaceholderText(_translate("MainWindow", "Dependency run (run this during installation)"))
        self.package_desc_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.package_desc_box.setPlaceholderText(_translate("MainWindow", "Package description. It should be a short text under 256 characters"))
        self.update_button.setText(_translate("MainWindow", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
