# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\RAZNOE\prgrming\horsy\Source\client\uis\horsy_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(292, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(292, 200))
        MainWindow.setMaximumSize(QtCore.QSize(292, 200))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setWindowOpacity(0.98)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setEnabled(True)
        self.login_button.setGeometry(QtCore.QRect(70, 140, 151, 50))
        self.login_button.setMinimumSize(QtCore.QSize(0, 50))
        self.login_button.setStyleSheet("QPushButton {\n"
"    color: rgb(204, 204, 204);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"    background-color: rgb(28, 30, 33);\n"
"    border-color: rgb(66, 143, 225);\n"
"}\n"
"QPushButton:hover{\n"
"    border-width: 2px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(50, 60, 63);\n"
"}\n"
"QPushButton:disabled{\n"
"    border-width: 0px;\n"
"    background-color: rgb(92, 99, 109);\n"
"}")
        self.login_button.setObjectName("login_button")
        self.email_box = QtWidgets.QLineEdit(self.centralwidget)
        self.email_box.setGeometry(QtCore.QRect(20, 20, 251, 51))
        self.email_box.setStyleSheet("background-color: rgb(74, 76, 83);\n"
"border-radius: 5px;    \n"
"color: rgb(242, 242, 242);")
        self.email_box.setObjectName("email_box")
        self.password_box = QtWidgets.QLineEdit(self.centralwidget)
        self.password_box.setGeometry(QtCore.QRect(20, 80, 251, 51))
        self.password_box.setStyleSheet("background-color: rgb(74, 76, 83);\n"
"border-radius: 5px;    \n"
"color: rgb(242, 242, 242);")
        self.password_box.setInputMask("")
        self.password_box.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_box.setObjectName("password_box")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Log in"))
        self.login_button.setText(_translate("MainWindow", "Log in"))
        self.email_box.setPlaceholderText(_translate("MainWindow", "email"))
        self.password_box.setPlaceholderText(_translate("MainWindow", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
