# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 425)
        MainWindow.setMinimumSize(QtCore.QSize(800, 120))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/horsy_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical,\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(30, 30, 30);\n"
"    width: 10px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical,\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(139, 139, 139);\n"
"    min-height: 30px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:vertical:pressed,\n"
"QScrollBar::handle:horizontal:hover,\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(149, 149, 149);\n"
"}\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical, \n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"    border-color: #303030;\n"
"    background-color: #2c2d2e;\n"
"    min-height: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-width: 2px;\n"
"    background-color: #323232;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #262728;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #434343;\n"
"    border-color: #0000;\n"
"}\n"
"\n"
"\n"
"QLineEdit, QTextBrowser, QPlainTextEdit, QTextEdit {\n"
"    min-height: 30px;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-style: solid;\n"
"    border-color: #303030;\n"
"    background-color: #242424;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QListWidget {\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-color: #303030;\n"
"    padding: 10px;\n"
"    background-color: #242424;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QListWidget:item {\n"
"    background-color: #242424;\n"
"    selection-color: white;\n"
"}\n"
"QListWidget:item:hover {\n"
"    background-color: #323232;\n"
"}\n"
"QListWidget:item:selected {\n"
"    background-color: #777777;\n"
"}\n"
"\n"
"\n"
"QTableWidget {\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-color: #303030;\n"
"    padding: 10px;\n"
"    background-color: #242424;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QTableWidget:item {\n"
"    background-color: #242424;\n"
"    selection-color: white;\n"
"}\n"
"QTableWidget:item:hover {\n"
"    background-color: #323232;\n"
"}\n"
"QTableWidget:item:selected {\n"
"    background-color: #777777;\n"
"}\n"
"\n"
"\n"
"QComboBox\n"
"{\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"    border-color: #303030;\n"
"    background-color: #2c2d2e;\n"
"    color: #ffffff;\n"
"}\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #434343;\n"
"    color: #656565;\n"
"    border-color: #434343;\n"
"}\n"
"QComboBox:hover\n"
"{\n"
"    background-color: #323232;\n"
"}\n"
"QComboBox:on\n"
"{\n"
"    background-color: #434343;\n"
"}\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #434343;\n"
"    color: #ffffff;\n"
"    selection-background-color: #777777;\n"
"    selection-color: white;\n"
"    outline: 0;\n"
"}\n"
"QComboBox::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-radius: 6px; \n"
"}\n"
"\n"
"\n"
"QTabBar::tab\n"
"{\n"
"    background-color: #2c2d2e;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-color: #303030;\n"
"    padding: 5px;\n"
"}\n"
"QTabBar::tab:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"}\n"
"QTabWidget::pane \n"
"{\n"
"    background-color: #a0a0a0;\n"
"    color: #ffffff;\n"
"    border: 3px solid;\n"
"    border-radius: 15px;\n"
"    border-color: #1c1c1c;\n"
"}\n"
"QTabBar::tab:selected\n"
"{\n"
"    background-color: #262728;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-color: #303030;\n"
"    padding: 5px;\n"
"}\n"
"QTabBar::tab:selected:disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"}\n"
"QTabBar::tab:!selected \n"
"{\n"
"    background-color: #262626;\n"
"}\n"
"QTabBar::tab:!selected:hover \n"
"{\n"
"    background-color: #323232;\n"
"}\n"
"QTabBar::tab:top:!selected \n"
"{\n"
"    margin-top: 3px;\n"
"}\n"
"QTabBar::tab:bottom:!selected \n"
"{\n"
"    margin-bottom: 3px;\n"
"}\n"
"QTabBar::tab:top, QTabBar::tab:bottom \n"
"{\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"QTabBar::tab:top:selected \n"
"{\n"
"    border-bottom-color: none;\n"
"}\n"
"QTabBar::tab:bottom:selected \n"
"{\n"
"    border-top-color: none;\n"
"}\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one \n"
"{\n"
"    margin-right: 0;\n"
"}\n"
"QTabBar::tab:left:!selected \n"
"{\n"
"    margin-right: 3px;\n"
"}\n"
"QTabBar::tab:right:!selected\n"
"{\n"
"    margin-left: 3px;\n"
"}\n"
"QTabBar::tab:left, QTabBar::tab:right \n"
"{\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"QTabBar::tab:left:selected \n"
"{\n"
"    border-left-color: none;\n"
"}\n"
"QTabBar::tab:right:selected \n"
"{\n"
"    border-right-color: none;\n"
"}\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one \n"
"{\n"
"    margin-bottom: 0;\n"
"}\n"
"\n"
"\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:#1e1d23;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #848484;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Ukraine))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QListWidget(self.centralwidget)
        self.menu.setMinimumSize(QtCore.QSize(64, 0))
        self.menu.setMaximumSize(QtCore.QSize(64, 16777215))
        self.menu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menu.setStyleSheet("\n"
"QListWidget {\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    background-color: #191919;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QListWidget:item {\n"
"    padding-left: 12px;\n"
"    height: 60px;\n"
"    background-color: #191919;\n"
"    selection-color: rgba(255, 255, 255);\n"
"}\n"
"QListWidget:item:hover {\n"
"    background-color: #323232;\n"
"}\n"
"QListWidget:item:selected {\n"
"    background-color: #262728;\n"
"}\n"
"")
        self.menu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.menu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.menu.setAutoScroll(False)
        self.menu.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.menu.setTabKeyNavigation(False)
        self.menu.setProperty("showDropIndicator", False)
        self.menu.setIconSize(QtCore.QSize(32, 32))
        self.menu.setTextElideMode(QtCore.Qt.ElideRight)
        self.menu.setResizeMode(QtWidgets.QListView.Fixed)
        self.menu.setObjectName("menu")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/installed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/explore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.menu.addItem(item)
        self.horizontalLayout.addWidget(self.menu)
        self.content = QtWidgets.QStackedWidget(self.centralwidget)
        self.content.setObjectName("content")
        self.installed_packages_page = QtWidgets.QWidget()
        self.installed_packages_page.setObjectName("installed_packages_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.installed_packages_page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.installed_packages_list = QtWidgets.QListWidget(self.installed_packages_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installed_packages_list.sizePolicy().hasHeightForWidth())
        self.installed_packages_list.setSizePolicy(sizePolicy)
        self.installed_packages_list.setMinimumSize(QtCore.QSize(50, 0))
        self.installed_packages_list.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.installed_packages_list.setObjectName("installed_packages_list")
        self.horizontalLayout_2.addWidget(self.installed_packages_list)
        self.installed_packages_from_list_lay = QtWidgets.QWidget(self.installed_packages_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installed_packages_from_list_lay.sizePolicy().hasHeightForWidth())
        self.installed_packages_from_list_lay.setSizePolicy(sizePolicy)
        self.installed_packages_from_list_lay.setMinimumSize(QtCore.QSize(0, 0))
        self.installed_packages_from_list_lay.setObjectName("installed_packages_from_list_lay")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.installed_packages_from_list_lay)
        self.verticalLayout.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.installed_package_desc = QtWidgets.QTextBrowser(self.installed_packages_from_list_lay)
        self.installed_package_desc.setObjectName("installed_package_desc")
        self.verticalLayout.addWidget(self.installed_package_desc)
        self.installed_buttons_lay = QtWidgets.QWidget(self.installed_packages_from_list_lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installed_buttons_lay.sizePolicy().hasHeightForWidth())
        self.installed_buttons_lay.setSizePolicy(sizePolicy)
        self.installed_buttons_lay.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.installed_buttons_lay.setObjectName("installed_buttons_lay")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.installed_buttons_lay)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.update_package_button = QtWidgets.QPushButton(self.installed_buttons_lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_package_button.sizePolicy().hasHeightForWidth())
        self.update_package_button.setSizePolicy(sizePolicy)
        self.update_package_button.setMinimumSize(QtCore.QSize(0, 32))
        self.update_package_button.setObjectName("update_package_button")
        self.horizontalLayout_3.addWidget(self.update_package_button)
        self.uninstall_package_button = QtWidgets.QPushButton(self.installed_buttons_lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uninstall_package_button.sizePolicy().hasHeightForWidth())
        self.uninstall_package_button.setSizePolicy(sizePolicy)
        self.uninstall_package_button.setMinimumSize(QtCore.QSize(0, 32))
        self.uninstall_package_button.setObjectName("uninstall_package_button")
        self.horizontalLayout_3.addWidget(self.uninstall_package_button)
        self.check_updates_button = QtWidgets.QPushButton(self.installed_buttons_lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_updates_button.sizePolicy().hasHeightForWidth())
        self.check_updates_button.setSizePolicy(sizePolicy)
        self.check_updates_button.setObjectName("check_updates_button")
        self.horizontalLayout_3.addWidget(self.check_updates_button)
        self.verticalLayout.addWidget(self.installed_buttons_lay)
        self.horizontalLayout_2.addWidget(self.installed_packages_from_list_lay)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 4)
        self.content.addWidget(self.installed_packages_page)
        self.browse_packages_page = QtWidgets.QWidget()
        self.browse_packages_page.setObjectName("browse_packages_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.browse_packages_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.search_bar_lay = QtWidgets.QWidget(self.browse_packages_page)
        self.search_bar_lay.setObjectName("search_bar_lay")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.search_bar_lay)
        self.horizontalLayout_5.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.search_box = QtWidgets.QLineEdit(self.search_bar_lay)
        self.search_box.setMinimumSize(QtCore.QSize(0, 32))
        self.search_box.setStyleSheet("")
        self.search_box.setObjectName("search_box")
        self.horizontalLayout_5.addWidget(self.search_box)
        self.search_button = QtWidgets.QPushButton(self.search_bar_lay)
        self.search_button.setMinimumSize(QtCore.QSize(70, 32))
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_5.addWidget(self.search_button)
        self.verticalLayout_3.addWidget(self.search_bar_lay)
        self.installation_progress = QtWidgets.QProgressBar(self.browse_packages_page)
        self.installation_progress.setProperty("value", 0)
        self.installation_progress.setTextVisible(False)
        self.installation_progress.setObjectName("installation_progress")
        self.verticalLayout_3.addWidget(self.installation_progress)
        self.downloading_main_file_progress = QtWidgets.QProgressBar(self.browse_packages_page)
        self.downloading_main_file_progress.setProperty("value", 0)
        self.downloading_main_file_progress.setTextVisible(False)
        self.downloading_main_file_progress.setObjectName("downloading_main_file_progress")
        self.verticalLayout_3.addWidget(self.downloading_main_file_progress)
        self.downloading_dependency_progress = QtWidgets.QProgressBar(self.browse_packages_page)
        self.downloading_dependency_progress.setProperty("value", 0)
        self.downloading_dependency_progress.setTextVisible(False)
        self.downloading_dependency_progress.setObjectName("downloading_dependency_progress")
        self.verticalLayout_3.addWidget(self.downloading_dependency_progress)
        self.search_content = QtWidgets.QWidget(self.browse_packages_page)
        self.search_content.setObjectName("search_content")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.search_content)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.search_results = QtWidgets.QWidget(self.search_content)
        self.search_results.setMinimumSize(QtCore.QSize(50, 0))
        self.search_results.setObjectName("search_results")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.search_results)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.search_packages_list = QtWidgets.QListWidget(self.search_results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_packages_list.sizePolicy().hasHeightForWidth())
        self.search_packages_list.setSizePolicy(sizePolicy)
        self.search_packages_list.setMinimumSize(QtCore.QSize(0, 0))
        self.search_packages_list.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.search_packages_list.setObjectName("search_packages_list")
        self.verticalLayout_9.addWidget(self.search_packages_list)
        self.verticalLayout_9.setStretch(0, 10)
        self.horizontalLayout_6.addWidget(self.search_results)
        self.search_packages_from_list_lay = QtWidgets.QWidget(self.search_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_packages_from_list_lay.sizePolicy().hasHeightForWidth())
        self.search_packages_from_list_lay.setSizePolicy(sizePolicy)
        self.search_packages_from_list_lay.setMinimumSize(QtCore.QSize(0, 0))
        self.search_packages_from_list_lay.setObjectName("search_packages_from_list_lay")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.search_packages_from_list_lay)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_package_desc = QtWidgets.QTextBrowser(self.search_packages_from_list_lay)
        self.search_package_desc.setObjectName("search_package_desc")
        self.verticalLayout_2.addWidget(self.search_package_desc)
        self.search_buttons_lay = QtWidgets.QWidget(self.search_packages_from_list_lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_buttons_lay.sizePolicy().hasHeightForWidth())
        self.search_buttons_lay.setSizePolicy(sizePolicy)
        self.search_buttons_lay.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.search_buttons_lay.setObjectName("search_buttons_lay")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.search_buttons_lay)
        self.horizontalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.install_package_button = QtWidgets.QPushButton(self.search_buttons_lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.install_package_button.sizePolicy().hasHeightForWidth())
        self.install_package_button.setSizePolicy(sizePolicy)
        self.install_package_button.setMinimumSize(QtCore.QSize(0, 32))
        self.install_package_button.setObjectName("install_package_button")
        self.horizontalLayout_4.addWidget(self.install_package_button)
        self.get_source_button = QtWidgets.QPushButton(self.search_buttons_lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_source_button.sizePolicy().hasHeightForWidth())
        self.get_source_button.setSizePolicy(sizePolicy)
        self.get_source_button.setMinimumSize(QtCore.QSize(0, 32))
        self.get_source_button.setObjectName("get_source_button")
        self.horizontalLayout_4.addWidget(self.get_source_button)
        self.like_button = QtWidgets.QPushButton(self.search_buttons_lay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.like_button.sizePolicy().hasHeightForWidth())
        self.like_button.setSizePolicy(sizePolicy)
        self.like_button.setObjectName("like_button")
        self.horizontalLayout_4.addWidget(self.like_button)
        self.dislike_button = QtWidgets.QPushButton(self.search_buttons_lay)
        self.dislike_button.setObjectName("dislike_button")
        self.horizontalLayout_4.addWidget(self.dislike_button)
        self.verticalLayout_2.addWidget(self.search_buttons_lay)
        self.horizontalLayout_6.addWidget(self.search_packages_from_list_lay)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 4)
        self.verticalLayout_3.addWidget(self.search_content)
        self.content.addWidget(self.browse_packages_page)
        self.upload_package_page = QtWidgets.QWidget()
        self.upload_package_page.setObjectName("upload_package_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.upload_package_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.before_uploading_message = QtWidgets.QLabel(self.upload_package_page)
        self.before_uploading_message.setObjectName("before_uploading_message")
        self.verticalLayout_4.addWidget(self.before_uploading_message)
        self.new_package_name_box = QtWidgets.QLineEdit(self.upload_package_page)
        self.new_package_name_box.setObjectName("new_package_name_box")
        self.verticalLayout_4.addWidget(self.new_package_name_box)
        self.new_package_desc_box = QtWidgets.QTextEdit(self.upload_package_page)
        self.new_package_desc_box.setObjectName("new_package_desc_box")
        self.verticalLayout_4.addWidget(self.new_package_desc_box)
        self.new_package_exe_url_box = QtWidgets.QLineEdit(self.upload_package_page)
        self.new_package_exe_url_box.setObjectName("new_package_exe_url_box")
        self.verticalLayout_4.addWidget(self.new_package_exe_url_box)
        self.new_package_command_box = QtWidgets.QLineEdit(self.upload_package_page)
        self.new_package_command_box.setObjectName("new_package_command_box")
        self.verticalLayout_4.addWidget(self.new_package_command_box)
        self.new_package_source_box = QtWidgets.QLineEdit(self.upload_package_page)
        self.new_package_source_box.setObjectName("new_package_source_box")
        self.verticalLayout_4.addWidget(self.new_package_source_box)
        self.new_package_dep_url_box = QtWidgets.QLineEdit(self.upload_package_page)
        self.new_package_dep_url_box.setObjectName("new_package_dep_url_box")
        self.verticalLayout_4.addWidget(self.new_package_dep_url_box)
        self.new_package_dep_run_box = QtWidgets.QLineEdit(self.upload_package_page)
        self.new_package_dep_run_box.setObjectName("new_package_dep_run_box")
        self.verticalLayout_4.addWidget(self.new_package_dep_run_box)
        self.upload_safety_warning_message = QtWidgets.QLabel(self.upload_package_page)
        self.upload_safety_warning_message.setWordWrap(True)
        self.upload_safety_warning_message.setObjectName("upload_safety_warning_message")
        self.verticalLayout_4.addWidget(self.upload_safety_warning_message)
        self.new_package_upload_button = QtWidgets.QPushButton(self.upload_package_page)
        self.new_package_upload_button.setObjectName("new_package_upload_button")
        self.verticalLayout_4.addWidget(self.new_package_upload_button)
        self.upload_result_label = QtWidgets.QLabel(self.upload_package_page)
        self.upload_result_label.setText("")
        self.upload_result_label.setObjectName("upload_result_label")
        self.verticalLayout_4.addWidget(self.upload_result_label)
        self.content.addWidget(self.upload_package_page)
        self.edit_package_page = QtWidgets.QWidget()
        self.edit_package_page.setObjectName("edit_package_page")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.edit_package_page)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.editable_packages_list = QtWidgets.QListWidget(self.edit_package_page)
        self.editable_packages_list.setMinimumSize(QtCore.QSize(50, 0))
        self.editable_packages_list.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.editable_packages_list.setObjectName("editable_packages_list")
        self.horizontalLayout_7.addWidget(self.editable_packages_list)
        self.edit_package_form_lay = QtWidgets.QWidget(self.edit_package_page)
        self.edit_package_form_lay.setObjectName("edit_package_form_lay")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.edit_package_form_lay)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.edit_package_name_box = QtWidgets.QLineEdit(self.edit_package_form_lay)
        self.edit_package_name_box.setReadOnly(True)
        self.edit_package_name_box.setObjectName("edit_package_name_box")
        self.verticalLayout_5.addWidget(self.edit_package_name_box)
        self.edit_package_desc_box = QtWidgets.QTextEdit(self.edit_package_form_lay)
        self.edit_package_desc_box.setObjectName("edit_package_desc_box")
        self.verticalLayout_5.addWidget(self.edit_package_desc_box)
        self.edit_package_exe_url_box = QtWidgets.QLineEdit(self.edit_package_form_lay)
        self.edit_package_exe_url_box.setObjectName("edit_package_exe_url_box")
        self.verticalLayout_5.addWidget(self.edit_package_exe_url_box)
        self.edit_package_command_box = QtWidgets.QLineEdit(self.edit_package_form_lay)
        self.edit_package_command_box.setObjectName("edit_package_command_box")
        self.verticalLayout_5.addWidget(self.edit_package_command_box)
        self.edit_package_source_box = QtWidgets.QLineEdit(self.edit_package_form_lay)
        self.edit_package_source_box.setObjectName("edit_package_source_box")
        self.verticalLayout_5.addWidget(self.edit_package_source_box)
        self.edit_package_dep_url_box = QtWidgets.QLineEdit(self.edit_package_form_lay)
        self.edit_package_dep_url_box.setObjectName("edit_package_dep_url_box")
        self.verticalLayout_5.addWidget(self.edit_package_dep_url_box)
        self.edit_package_dep_run_box = QtWidgets.QLineEdit(self.edit_package_form_lay)
        self.edit_package_dep_run_box.setObjectName("edit_package_dep_run_box")
        self.verticalLayout_5.addWidget(self.edit_package_dep_run_box)
        self.edit_packages_buttons_lay = QtWidgets.QWidget(self.edit_package_form_lay)
        self.edit_packages_buttons_lay.setObjectName("edit_packages_buttons_lay")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.edit_packages_buttons_lay)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.edit_package_button = QtWidgets.QPushButton(self.edit_packages_buttons_lay)
        self.edit_package_button.setObjectName("edit_package_button")
        self.horizontalLayout_8.addWidget(self.edit_package_button)
        self.force_upgrade_button = QtWidgets.QPushButton(self.edit_packages_buttons_lay)
        self.force_upgrade_button.setObjectName("force_upgrade_button")
        self.horizontalLayout_8.addWidget(self.force_upgrade_button)
        self.verticalLayout_5.addWidget(self.edit_packages_buttons_lay)
        self.edit_result_label = QtWidgets.QLabel(self.edit_package_form_lay)
        self.edit_result_label.setText("")
        self.edit_result_label.setObjectName("edit_result_label")
        self.verticalLayout_5.addWidget(self.edit_result_label)
        self.horizontalLayout_7.addWidget(self.edit_package_form_lay)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 4)
        self.content.addWidget(self.edit_package_page)
        self.account_settings_page = QtWidgets.QWidget()
        self.account_settings_page.setObjectName("account_settings_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.account_settings_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.new_login_lay = QtWidgets.QWidget(self.account_settings_page)
        self.new_login_lay.setObjectName("new_login_lay")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.new_login_lay)
        self.verticalLayout_7.setContentsMargins(200, 0, 200, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.login_mail_box = QtWidgets.QLineEdit(self.new_login_lay)
        self.login_mail_box.setObjectName("login_mail_box")
        self.verticalLayout_7.addWidget(self.login_mail_box)
        self.login_password_box = QtWidgets.QLineEdit(self.new_login_lay)
        self.login_password_box.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.login_password_box.setObjectName("login_password_box")
        self.verticalLayout_7.addWidget(self.login_password_box)
        self.login_button = QtWidgets.QPushButton(self.new_login_lay)
        self.login_button.setObjectName("login_button")
        self.verticalLayout_7.addWidget(self.login_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.verticalLayout_6.addWidget(self.new_login_lay)
        self.login_lay = QtWidgets.QWidget(self.account_settings_page)
        self.login_lay.setObjectName("login_lay")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.login_lay)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.logged_in_name_box = QtWidgets.QLineEdit(self.login_lay)
        self.logged_in_name_box.setReadOnly(True)
        self.logged_in_name_box.setObjectName("logged_in_name_box")
        self.horizontalLayout_10.addWidget(self.logged_in_name_box)
        self.logout_button = QtWidgets.QPushButton(self.login_lay)
        self.logout_button.setMinimumSize(QtCore.QSize(130, 32))
        self.logout_button.setObjectName("logout_button")
        self.horizontalLayout_10.addWidget(self.logout_button)
        self.verticalLayout_6.addWidget(self.login_lay)
        self.change_email_lay = QtWidgets.QWidget(self.account_settings_page)
        self.change_email_lay.setObjectName("change_email_lay")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.change_email_lay)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.change_email_box = QtWidgets.QLineEdit(self.change_email_lay)
        self.change_email_box.setObjectName("change_email_box")
        self.horizontalLayout_9.addWidget(self.change_email_box)
        self.change_email_button = QtWidgets.QPushButton(self.change_email_lay)
        self.change_email_button.setMinimumSize(QtCore.QSize(130, 32))
        self.change_email_button.setObjectName("change_email_button")
        self.horizontalLayout_9.addWidget(self.change_email_button)
        self.verticalLayout_6.addWidget(self.change_email_lay)
        self.change_password_lay = QtWidgets.QWidget(self.account_settings_page)
        self.change_password_lay.setObjectName("change_password_lay")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.change_password_lay)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.old_password_box = QtWidgets.QLineEdit(self.change_password_lay)
        self.old_password_box.setObjectName("old_password_box")
        self.verticalLayout_8.addWidget(self.old_password_box)
        self.change_pass_lay_new = QtWidgets.QWidget(self.change_password_lay)
        self.change_pass_lay_new.setObjectName("change_pass_lay_new")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.change_pass_lay_new)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.new_password_box = QtWidgets.QLineEdit(self.change_pass_lay_new)
        self.new_password_box.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.new_password_box.setObjectName("new_password_box")
        self.horizontalLayout_11.addWidget(self.new_password_box)
        self.change_password_button = QtWidgets.QPushButton(self.change_pass_lay_new)
        self.change_password_button.setMinimumSize(QtCore.QSize(130, 32))
        self.change_password_button.setObjectName("change_password_button")
        self.horizontalLayout_11.addWidget(self.change_password_button)
        self.verticalLayout_8.addWidget(self.change_pass_lay_new)
        self.verticalLayout_6.addWidget(self.change_password_lay)
        self.account_settings_vert_spacer_widget = QtWidgets.QWidget(self.account_settings_page)
        self.account_settings_vert_spacer_widget.setObjectName("account_settings_vert_spacer_widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.account_settings_vert_spacer_widget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem2 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.verticalLayout_6.addWidget(self.account_settings_vert_spacer_widget)
        self.content.addWidget(self.account_settings_page)
        self.gui_settings_page = QtWidgets.QWidget()
        self.gui_settings_page.setObjectName("gui_settings_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.gui_settings_page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.settings_lay = QtWidgets.QWidget(self.gui_settings_page)
        self.settings_lay.setObjectName("settings_lay")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.settings_lay)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.choose_animation_label = QtWidgets.QLabel(self.settings_lay)
        self.choose_animation_label.setObjectName("choose_animation_label")
        self.verticalLayout_10.addWidget(self.choose_animation_label)
        self.choose_animation_box = QtWidgets.QComboBox(self.settings_lay)
        self.choose_animation_box.setMinimumSize(QtCore.QSize(0, 30))
        self.choose_animation_box.setObjectName("choose_animation_box")
        self.choose_animation_box.addItem("")
        self.choose_animation_box.addItem("")
        self.choose_animation_box.addItem("")
        self.choose_animation_box.addItem("")
        self.choose_animation_box.addItem("")
        self.verticalLayout_10.addWidget(self.choose_animation_box)
        self.choose_theme_label = QtWidgets.QLabel(self.settings_lay)
        self.choose_theme_label.setObjectName("choose_theme_label")
        self.verticalLayout_10.addWidget(self.choose_theme_label)
        self.choose_theme_box = QtWidgets.QComboBox(self.settings_lay)
        self.choose_theme_box.setMinimumSize(QtCore.QSize(0, 30))
        self.choose_theme_box.setObjectName("choose_theme_box")
        self.choose_theme_box.addItem("")
        self.choose_theme_box.addItem("")
        self.choose_theme_box.addItem("")
        self.verticalLayout_10.addWidget(self.choose_theme_box)
        self.add_vt_key_label = QtWidgets.QLabel(self.settings_lay)
        self.add_vt_key_label.setObjectName("add_vt_key_label")
        self.verticalLayout_10.addWidget(self.add_vt_key_label)
        self.add_vt_key_box = QtWidgets.QLineEdit(self.settings_lay)
        self.add_vt_key_box.setObjectName("add_vt_key_box")
        self.verticalLayout_10.addWidget(self.add_vt_key_box)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.verticalLayout_11.addWidget(self.settings_lay)
        self.save_settings_button = QtWidgets.QPushButton(self.gui_settings_page)
        self.save_settings_button.setObjectName("save_settings_button")
        self.verticalLayout_11.addWidget(self.save_settings_button)
        self.content.addWidget(self.gui_settings_page)
        self.horizontalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.menu.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "horsy"))
        __sortingEnabled = self.menu.isSortingEnabled()
        self.menu.setSortingEnabled(False)
        item = self.menu.item(0)
        item.setText(_translate("MainWindow", "Close menu"))
        item = self.menu.item(1)
        item.setText(_translate("MainWindow", "Installed packages"))
        item = self.menu.item(2)
        item.setText(_translate("MainWindow", "Explore packages"))
        item = self.menu.item(3)
        item.setText(_translate("MainWindow", "Upload package"))
        item = self.menu.item(4)
        item.setText(_translate("MainWindow", "Edit packages"))
        item = self.menu.item(5)
        item.setText(_translate("MainWindow", "Account settings"))
        item = self.menu.item(6)
        item.setText(_translate("MainWindow", "Settings of GUI"))
        self.menu.setSortingEnabled(__sortingEnabled)
        self.update_package_button.setText(_translate("MainWindow", "Update"))
        self.uninstall_package_button.setText(_translate("MainWindow", "Uninstall"))
        self.check_updates_button.setText(_translate("MainWindow", "Check all updates"))
        self.search_box.setPlaceholderText(_translate("MainWindow", "Search packages (powered by Algolia)"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.install_package_button.setText(_translate("MainWindow", "Install"))
        self.get_source_button.setText(_translate("MainWindow", "Get source"))
        self.like_button.setText(_translate("MainWindow", "👍"))
        self.dislike_button.setText(_translate("MainWindow", "👎"))
        self.before_uploading_message.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Before starting, please make sure you have done your project and </span><span style=\" font-size:9pt; font-weight:600;\">uploaded</span><span style=\" font-size:9pt;\"> it to any hosting service or file sharing service</span></p></body></html>"))
        self.new_package_name_box.setPlaceholderText(_translate("MainWindow", "*Package name (lowercase letters, underscores, dashes)"))
        self.new_package_desc_box.setPlaceholderText(_translate("MainWindow", "*Package description. It should be a short text under 256 characters"))
        self.new_package_exe_url_box.setPlaceholderText(_translate("MainWindow", "*Url of executable (ends on .zip, .exe, .py, .msi, .js, .bat, .cmd, .ps1"))
        self.new_package_command_box.setPlaceholderText(_translate("MainWindow", "*Main executable command ($appdir$\\\\file.exe, python $appdir$\\\\main.py, cd $appdir$ & node index.js, etc.)"))
        self.new_package_source_box.setPlaceholderText(_translate("MainWindow", "Url of source (project on GitHub, source archive)"))
        self.new_package_dep_url_box.setPlaceholderText(_translate("MainWindow", "Dependency URL (installer of interpreter, etc.)"))
        self.new_package_dep_run_box.setPlaceholderText(_translate("MainWindow", "Dependency command (run this during installation, it can be filename of downloaded installer, etc)"))
        self.upload_safety_warning_message.setText(_translate("MainWindow", "We don\'t moderate any apps and we won\'t delete your app, if it is not doesn\'t match some rules. But, if your app uses server vulnerabilities or hinders server work, we will delete your app. Keep in mind, that we don\'t responsible for your apps, but we advise you to share only working and safe apps on horsy"))
        self.new_package_upload_button.setText(_translate("MainWindow", "Upload"))
        self.edit_package_name_box.setPlaceholderText(_translate("MainWindow", "*Package name (lowercase letters, underscores, dashes)"))
        self.edit_package_desc_box.setPlaceholderText(_translate("MainWindow", "*Package description. It should be a short text under 256 characters"))
        self.edit_package_exe_url_box.setPlaceholderText(_translate("MainWindow", "*Url of executable (ends on .zip, .exe, .py, .msi, .js, .bat, .cmd, .ps1"))
        self.edit_package_command_box.setPlaceholderText(_translate("MainWindow", "*Main executable command ($appdir$\\\\file.exe, python $appdir$\\\\main.py, cd $appdir$ & node index.js, etc.)"))
        self.edit_package_source_box.setPlaceholderText(_translate("MainWindow", "Url of source (project on GitHub, source archive)"))
        self.edit_package_dep_url_box.setPlaceholderText(_translate("MainWindow", "Dependency URL (installer of interpreter, etc.)"))
        self.edit_package_dep_run_box.setPlaceholderText(_translate("MainWindow", "Dependency command (run this during installation, it can be filename of downloaded installer, etc)"))
        self.edit_package_button.setText(_translate("MainWindow", "Edit"))
        self.force_upgrade_button.setText(_translate("MainWindow", "Force users to upgrade this package"))
        self.login_mail_box.setPlaceholderText(_translate("MainWindow", "email"))
        self.login_password_box.setPlaceholderText(_translate("MainWindow", "Password"))
        self.login_button.setText(_translate("MainWindow", "Log in"))
        self.logged_in_name_box.setPlaceholderText(_translate("MainWindow", "Logged in as: "))
        self.logout_button.setText(_translate("MainWindow", "Log out"))
        self.change_email_box.setPlaceholderText(_translate("MainWindow", "email"))
        self.change_email_button.setText(_translate("MainWindow", "Change e-mail"))
        self.old_password_box.setPlaceholderText(_translate("MainWindow", "Old password"))
        self.new_password_box.setPlaceholderText(_translate("MainWindow", "New password"))
        self.change_password_button.setText(_translate("MainWindow", "Change password"))
        self.choose_animation_label.setText(_translate("MainWindow", "Choose menu animation"))
        self.choose_animation_box.setItemText(0, _translate("MainWindow", "InOutQuart"))
        self.choose_animation_box.setItemText(1, _translate("MainWindow", "InOutBack"))
        self.choose_animation_box.setItemText(2, _translate("MainWindow", "InOutBounce"))
        self.choose_animation_box.setItemText(3, _translate("MainWindow", "OutBack"))
        self.choose_animation_box.setItemText(4, _translate("MainWindow", "OutElastic"))
        self.choose_theme_label.setText(_translate("MainWindow", "Theme (requires app restart)"))
        self.choose_theme_box.setItemText(0, _translate("MainWindow", "Dark gray"))
        self.choose_theme_box.setItemText(1, _translate("MainWindow", "Black"))
        self.choose_theme_box.setItemText(2, _translate("MainWindow", "Black acrylic"))
        self.add_vt_key_label.setText(_translate("MainWindow", "Add virustotal api key"))
        self.save_settings_button.setText(_translate("MainWindow", "Save settings"))
import ui.img.images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
